name: CI

on:
  push:
    branches:
      - main
      - develop
      - features*

jobs:
  develop:
    name: Development processes
    runs-on: ubuntu-22.04
	if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - name: Check Repository
        uses: actions/checkout@v4
	 
	  - name: Set up QEMU
		uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
		uses: docker/setup-buildx-action@v3

      - name: Login into docker hub
		uses: docker/login-action@v3
		with:
			username: ${{secrets.DOCKER_USERNAME}}
			password: ${{secrets.DOCKER_PASSWORD}}

	  - name: Deploy mytelebot to dockerhub
		uses: docker/build-push-action@v5
		with:
			context: "{{defaultContext}}"
			push: true
			tags: ${{secrets.DOCKER_USERNAME}}/mytelebot:${{secrets.DOCKER_TAGS_MYTELEBOT}}
